def holiday():
    verbWithIng = input("Verb ending with –ing: ")
    aNounOfAPlace = input("A noun that’s a place: ")
    aHolidaySong = input("A holiday song: ")
    adjective = input("Adjective: ")
    adjective2 = input("2nd adjective: ")
    yourFriend = input("Your friend: ")
    verbWithEd = input("Verb ending with -ed: ")
    verbWithEd2 = input("2nd Verb ending with -ed: ")
    amountOfTime = input("An amount of time: ")
    verb = input("Verb: ")
    pluralNoun = input("Plural noun: ")
    aPlaceUpTop = input("A place up top: ")
    aRelative = input("A relative: ")
    aNumber = input("A number: ")
    aFoodItem = input("A food item: ")
    aRelative2 = input("A relative: ")
    verbWithEd3 = input("3rd Verb ending with -ed: ")
    noun = input("Noun: ")
    aSinger = input("A singer: ")
    adjective3 = input("3rd adjective: ")
    aPerson = input("A person: ")
    aMessyFood = input("A messy food:: ")
    aBodyPart = input("A body part: ")
    amountOfTime2 = input("Amount of time: ")
    aHolidayFood = input("A holiday food: ")

    print("\nI was " + verbWithIng + " at the " + aNounOfAPlace + " the other day when I heard")
    print(aHolidaySong + " come on the radio. I was feeling really " + adjective + " and")
    print("I’m pretty sure I looked super " + adjective2 + " because " + yourFriend + " walked in and")
    print("almost " + verbWithEd + ". Seriously, she " + verbWithEd2 + " for close to " + amountOfTime + "!")
    print("\nThis time every year I " + verb + " all the time because I get really exciting thinking")
    print("about holiday " + pluralNoun + "! That’s why I was sitting at the " + aPlaceUpTop + ":")
    print(" I was really hoping " + aRelative + " would come by and give me at least " + aNumber)
    print(" pieces of holiday " + aFoodItem + "!")
    print("\nThat didn’t happen, but suddenly " + aRelative2 + " " + verbWithEd3 + " by in a")
    print("huge " + noun + " on wheels dressed up as " + aSinger + ". I know " + adjective3)
    print("things happen around the holidays, but this didn’t make any sense! I picked up")
    print("the phone to call " + aPerson + ", but the phone turned into a big pile of " + aMessyFood)
    print("and dripped all the way down to my " + aBodyPart + "!")
    print("\nThen my alarm clock went off for about " + amountOfTime2 + ". It was all a dream! I had")
    print("a ton of " + aHolidayFood + " before I went to sleep. Maybe that’s what gave me the crazy dream!")

def theFunPark():
    adjective = input("Adjective: ")
    pluralNoun = input("Plural noun: ")
    noun = input("Noun: ")
    adverb = input("Adverb: ")
    number = input("Number: ")
    pastTenseVerb = input("A past tense verb: ")
    adjectiveWithEst = input("Adjective ending with -est: ")
    pastTenseVerb2 = input("2nd past tense verb: ")
    adverb2 = input("2nd adverb: ")
    adjective2 = input("2nd adjective: ")

    print("Today, my fabulous camp group went to a (an)" + adjective + " amusement park. It was a")
    print("fun park with lots of cool " + pluralNoun + "and enjoyable play structures. When we got there, my")
    print("kind counselor shouted loudly, \"Everybody off the " + noun + ".\" We all pushed out in a terrible")
    print("hurry. My counselor handed out yellow tickets, and we scurried in. I was so excited! I couldn't figure out")
    print("what exciting thing to do first. I saw a scary rollercoaster I really liked so, I " + adverb + " ran")
    print("over to get in the long line that had about " + number + " people in it. When I finally")
    print("got on the roller coaster I was " + pastTenseVerb + ". In fact I was so nervous my two knees")
    print("were knocking together. This was the " + adjectiveWithEst + " ride I had ever been on! In about two")
    print("minutes I heard the crank and grinding of the gears.That’s when the ride began! When I got to the bottom,")
    print("I was a little " + pastTenseVerb2 + " but I was proud of myself. The rest of the day went")
    print(adverb2 + ". It was a(n) " + adjective2 + " day at the fun park.")