def holiday():
    verbWithIng = input("Verb ending with –ing: ")
    aNounOfAPlace = input("A noun that’s a place: ")
    aHolidaySong = input("A holiday song: ")
    adjective = input("Adjective: ")
    adjective2 = input("2nd adjective: ")
    yourFriend = input("Your friend: ")
    verbWithEd = input("Verb ending with -ed: ")
    verbWithEd2 = input("2nd Verb ending with -ed: ")
    amountOfTime = input("An amount of time: ")
    verb = input("Verb: ")
    pluralNoun = input("Plural noun: ")
    aPlace = input("A place: ")
    aRelative = input("A relative: ")
    aNumber = input("A number: ")
    aFoodItem = input("A food item: ")
    aRelative2 = input("A relative: ")
    verbWithEd3 = input("3rd Verb ending with -ed: ")
    noun = input("Noun: ")
    aSinger = input("A singer: ")
    adjective3 = input("3rd adjective: ")
    aPerson = input("A person: ")
    aMessyFood = input("A messy food:: ")
    aBodyPart = input("A body part: ")
    amountOfTime2 = input("Amount of time: ")
    aHolidayFood = input("A holiday food: ")

    print("\nI was " + verbWithIng + " at the " + aNounOfAPlace + " the other day when I heard")
    print(aHolidaySong + " come on the radio. I was feeling really " + adjective + " and")
    print("I’m pretty sure I looked super " + adjective2 + " because " + yourFriend + " walked in and")
    print("almost " + verbWithEd + ". Seriously, she " + verbWithEd2 + " for close to " + amountOfTime + "!")
    print("\nThis time every year I " + verb + " all the time because I get really exciting thinking")
    print("about holiday " + pluralNoun + "! That’s why I was sitting at the " + aPlace + ":")
    print(" I was really hoping " + aRelative + " would come by and give me at least " + aNumber)
    print(" pieces of holiday " + aFoodItem + "!")
    print("\nThat didn’t happen, but suddenly " + aRelative2 + " " + verbWithEd3 + " by in a")
    print("huge " + noun + " on wheels dressed up as " + aSinger + ". I know " + adjective3)
    print("things happen around the holidays, but this didn’t make any sense! I picked up")
    print("the phone to call " + aPerson + ", but the phone turned into a big pile of " + aMessyFood)
    print("and dripped all the way down to my " + aBodyPart + "!")
    print("\nThen my alarm clock went off for about " + amountOfTime2 + ". It was all a dream! I had")
    print("a ton of " + aHolidayFood + " before I went to sleep. Maybe that’s what gave me the crazy dream!")